development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://wmepqqmbjowexj:4jQ1nDHpYHnUVTWGM7g4J_XaCz@ec2-54-163-230-103.compute-1.amazonaws.com:5432/dg9jk112n2m3d
