# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3fb955b7097cd48e6aa95731e79b20573f2fb07815b849809f0d93dced0867ab2a1cd6d879e2f227cb3f86535d0fcada71ad6800cd2771cc3a942d6d79923456

test:
  secret_key_base: 9c8da7c0c8a389f61e2a51010aa44f67d4ebea87386ec5c77f2a05bf09269921f01da737244908564b3ae6955ad341a9bcf35b3b3f75b8b4aaaf79ccbe41d919

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
